### PR TITLE
Finish Verison

### PR DESCRIPTION
**Pull request by hagan199**
updated well description on the project.
Get a list of items with a unique item id (or generate the unique id).
For a given item, get detailed information about it.
Added number of items (home).
When the page loads, show the item likes and combines them with the data from the base API.
This task does not include displaying the likes button (heart icon on the wireframe) for each item.
 
image

### CODE REVIEW

**Review by franclobo — COMMENTED** [review]
Hi @hagan199, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has some errors:

1. It is evident that has linter errors.
2. Doesn't have a descriptive PR with a meaningful title and a summary of the changes in the current branch.
3. This is a GROUP CAPSTONE - while working, students were supposed to give reviews to each other and merge their feature branches into the dev branch. The pull request link that you should submit should be opened from the dev branch into the main branch and include all the changes. Please review [this article](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/code-review/articles/code_review_flow_group_projects.md)
4. Doesn't have a professional README file.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Review by afanimartin — CHANGES_REQUESTED** [review]
Hi @hagan199, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has failing linter checks. Please fix that before re-sending for another review.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

## Find me on slack
### Martin Afani

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by Whoistolu — COMMENTED** [review]
Hi @hagan199 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

### You have submitted a project with no descriptive PR title and no PR description. A pull request title and description should effectively communicate the purpose, changes, and context of the pull request to reviewers. Pull Request Title: Feature/Change] Brief Description of the Pull Request and the Pull Request Description should state the changes that took place in the project.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @whoistolu in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by Strangeal — COMMENTED** [review]
Hi @hagan199, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't use proper git-flow, The final code PR should be opened from the dev branch into the main instead of the final-version to dev. Please make sure to fix this issue and resubmit it for review.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Pull request merged**
